### ISSUE TITLE
Use docker/login-action instead of manual step in each actions

### ISSUE THREAD

**Issue by bgauduch** [zenika-open-source/terraform-aws-cli#60]
Notes:

- require a personal access token in place of the password

Exemple :

```yaml
  - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
```
